"""OpenSpec agent prompts for Cursor, Antigravity (.agent) and Amazon Q stay identical.

The copies are generated by the OpenSpec CLI (`openspec update`), which owns the text
between the OPENSPEC:START/END markers. Edit them by upgrading OpenSpec and running
`openspec update`, never by hand in one of the directories.
"""

import pathlib
import re

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
COPIES = {
    "cursor": ROOT / ".cursor" / "commands",
    "agent": ROOT / ".agent" / "workflows",
    "amazonq": ROOT / ".amazonq" / "prompts",
}
MANAGED = re.compile(r"<!-- OPENSPEC:START -->(.*?)<!-- OPENSPEC:END -->", re.S)


@pytest.mark.parametrize("name", ["openspec-proposal", "openspec-apply", "openspec-archive"])
def test_managed_prompt_text_is_identical(name):
    bodies = {}
    for tool, directory in COPIES.items():
        path = directory / f"{name}.md"
        if not path.exists():
            pytest.skip(f"{path.relative_to(ROOT)} not present")
        match = MANAGED.search(path.read_text(encoding="utf8"))
        assert match, f"{path.relative_to(ROOT)} has no OpenSpec managed block"
        bodies[tool] = match.group(1).strip()
    assert len(set(bodies.values())) == 1, f"{name} differs between {sorted(bodies)}"
