"""Generate the Python SDK API reference page from docstrings.

Usage:
    python scripts/generate_sdk_reference.py          # write docs/docs/integrations/sdk-reference.md
    python scripts/generate_sdk_reference.py --check  # exit 1 when the page is stale (CI)

Documents the public classes of the SDK (``Dataset`` and the result types) with their
signatures and Google-style docstrings (summary, ``Args``, ``Returns``, ``Raises``,
``Example``). Public names without a docstring are an error, so the page cannot silently
miss a method.
"""

from __future__ import annotations

import argparse
import inspect
import pathlib
import re
import sys
from typing import Any

from undatum.sdk import Dataset
from undatum.sdk.results import QueryResult, StatsResult

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAGE = ROOT / "docs" / "docs" / "integrations" / "sdk-reference.md"
CLASSES = (Dataset, StatsResult, QueryResult)
SECTIONS = ("Args", "Returns", "Yields", "Raises", "Example", "Examples", "Note")

HEADER = """---
title: "Python SDK reference"
description: "Every public Dataset method, generated from the docstrings"
---
<!-- Generated by scripts/generate_sdk_reference.py from the docstrings; do not edit by hand. -->

# Python SDK reference

Generated from the docstrings of `undatum.sdk`. For a guided introduction see
[Python SDK](/integrations/sdk).

```python
from undatum import Dataset
```
"""


def _escape(text: str) -> str:
    for char, entity in (("<", "&lt;"), (">", "&gt;"), ("{", "&#123;"), ("}", "&#125;")):
        text = text.replace(char, entity)
    return text


def _inline(text: str) -> str:
    """Escape prose but keep ``code`` spans intact (rST double backticks become Markdown)."""
    parts = re.split(r"(``[^`]+``|`[^`]+`)", text)
    out = []
    for part in parts:
        if part.startswith("``"):
            out.append(f"`{part[2:-2]}`")
        elif part.startswith("`"):
            out.append(part)
        else:
            out.append(_escape(part))
    return "".join(out)


def parse_docstring(doc: str) -> tuple[list[str], dict[str, list[str]]]:
    """Split a Google-style docstring into description lines and named sections."""
    lines = inspect.cleandoc(doc).splitlines()
    description: list[str] = []
    sections: dict[str, list[str]] = {}
    current: list[str] = description
    for line in lines:
        header = line.rstrip(":").strip()
        if line.endswith(":") and header in SECTIONS and not line.startswith(" "):
            current = sections.setdefault(header, [])
            continue
        current.append(line)
    return description, sections


def _entries(lines: list[str]) -> list[tuple[str, str]]:
    """Parse ``name: text`` entries with indented continuation lines."""
    entries: list[tuple[str, str]] = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        indent = len(line) - len(line.lstrip())
        match = re.match(r"^(\*{0,2}[\w.]+)(?: \(([^)]*)\))?:\s*(.*)$", stripped)
        if match and (indent <= 4 or not entries):
            entries.append((match.group(1), match.group(3)))
        elif entries:
            name, text = entries[-1]
            entries[-1] = (name, f"{text} {stripped}".strip())
    return entries


def render_doc(doc: str) -> list[str]:
    """Render a docstring as Markdown lines."""
    description, sections = parse_docstring(doc)
    out = [_inline(line) if line.strip() else "" for line in description]
    out.append("")
    if "Args" in sections:
        out += ["| Parameter | Description |", "|-----------|-------------|"]
        for name, text in _entries(sections["Args"]):
            cell = _inline(text).replace("|", "\\|")
            out.append(f"| `{name}` | {cell} |")
        out.append("")
    for title in ("Returns", "Yields"):
        if title in sections:
            text = " ".join(line.strip() for line in sections[title] if line.strip())
            out += [f"**{title}:** {_inline(text)}", ""]
    if "Raises" in sections:
        out.append("**Raises:**")
        out.append("")
        for name, text in _entries(sections["Raises"]):
            out.append(f"- `{name}`: {_inline(text)}")
        out.append("")
    for title in ("Example", "Examples"):
        if title in sections:
            code = [
                line.strip()[4:] if line.strip().startswith(">>> ") else line.strip()
                for line in sections[title]
                if line.strip()
            ]
            out += ["```python", *code, "```", ""]
    if "Note" in sections:
        text = " ".join(line.strip() for line in sections["Note"] if line.strip())
        out += [f":::note\n{_inline(text)}\n:::", ""]
    return out


def _annotation(annotation: Any) -> str:
    if isinstance(annotation, str):
        return annotation
    text = inspect.formatannotation(annotation)
    return re.sub(r"\b(?:typing|collections\.abc)\.", "", text)


def _signature(name: str, member: Any) -> str:
    """Format ``member``'s signature as written in the source (without self/cls)."""
    signature = inspect.signature(member)
    params = []
    previous = None
    for param in signature.parameters.values():
        if param.name in ("self", "cls"):
            continue
        if param.kind is param.KEYWORD_ONLY and previous not in (
            param.KEYWORD_ONLY,
            param.VAR_POSITIONAL,
        ):
            params.append("*")
        text = param.name
        if param.kind is param.VAR_POSITIONAL:
            text = "*" + text
        elif param.kind is param.VAR_KEYWORD:
            text = "**" + text
        if param.annotation is not param.empty and param.kind not in (
            param.VAR_POSITIONAL,
            param.VAR_KEYWORD,
        ):
            text += f": {_annotation(param.annotation)}"
        if param.default is not param.empty:
            text += f" = {param.default!r}"
        params.append(text)
        previous = param.kind
    result = f"{name}({', '.join(params)})"
    if signature.return_annotation is not signature.empty:
        result += f" -> {_annotation(signature.return_annotation)}"
    return result


def _members(cls: type) -> list[tuple[str, Any, str]]:
    """Public methods and properties defined on ``cls``, in source order."""
    members = []
    for name, value in cls.__dict__.items():
        if name.startswith("_"):
            continue
        if isinstance(value, property):
            members.append((name, value.fget, "property"))
        elif isinstance(value, (classmethod, staticmethod)):
            members.append((name, value.__func__, type(value).__name__))
        elif inspect.isfunction(value):
            members.append((name, value, "method"))
    return members


def render_page() -> str:
    """Return the full reference page."""
    out = [HEADER]
    missing = []
    for cls in CLASSES:
        out += [f"## `{cls.__name__}`", ""]
        out += render_doc(cls.__doc__ or "")
        for name, member, kind in _members(cls):
            doc = inspect.getdoc(member)
            if not doc:
                missing.append(f"{cls.__name__}.{name}")
                continue
            title = name if kind == "property" else _signature(name, member)
            label = f" *({kind})*" if kind in ("classmethod", "property") else ""
            out += [f"### `{cls.__name__}.{title}`{label}", ""]
            out += render_doc(doc)
    if missing:
        raise SystemExit("Public SDK members without a docstring: " + ", ".join(missing))
    text = "\n".join(out)
    return re.sub(r"\n{3,}", "\n\n", text).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when the page is stale")
    args = parser.parse_args(argv)
    page = render_page()
    current = PAGE.read_text(encoding="utf8") if PAGE.exists() else ""
    if page == current:
        return 0
    if args.check:
        print(f"{PAGE.relative_to(ROOT)} is stale; run python scripts/generate_sdk_reference.py")
        return 1
    PAGE.write_text(page, encoding="utf8")
    print(f"Wrote {PAGE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
