"""Generate the option reference on every command page from the CLI itself.

Usage:
    python scripts/generate_cli_reference.py          # update docs/docs/commands/*.md
    python scripts/generate_cli_reference.py --check  # exit 1 when a page is stale (CI)

Each command page keeps its hand-written introduction and examples. The block between

    <!-- BEGIN GENERATED: reference -->
    <!-- END GENERATED: reference -->

is rewritten from the Click command tree: a capability line (``undatum/cli/capabilities.py``
plus the presence of ``--engine``), usage, arguments, options with defaults, and deprecated
spellings. Pages without the markers get the block appended; commands without a page get
a new page. Hidden (deprecated) commands are skipped.
"""

from __future__ import annotations

import argparse
import logging
import pathlib
import re
import sys
from collections.abc import Iterator
from typing import Any

logging.disable(logging.CRITICAL)

import typer.main  # noqa: E402

from undatum.cli.capabilities import CAPABILITIES  # noqa: E402
from undatum.core import app  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAGES = ROOT / "docs" / "docs" / "commands"
BEGIN = "<!-- BEGIN GENERATED: reference -->"
END = "<!-- END GENERATED: reference -->"
NOTE = "<!-- Generated by scripts/generate_cli_reference.py from the CLI; do not edit by hand. -->"
ENGINES = "auto, duckdb, python"


def _escape(text: str) -> str:
    """Make help text safe inside a Markdown table cell in MDX."""
    text = " ".join(text.split())
    for char, entity in (("<", "&lt;"), (">", "&gt;"), ("{", "&#123;"), ("}", "&#125;")):
        text = text.replace(char, entity)
    return text.replace("|", "\\|")


def _help(param: Any) -> str:
    text = getattr(param, "help", None) or ""
    return _escape(re.sub(r"\s*\[default: [^\]]*\]", "", text))


def _default(param: Any) -> str:
    default = param.default
    if getattr(param, "is_flag", False):
        if default is None:  # tri-state switch: the command decides
            return ""
        if getattr(param, "secondary_opts", None):
            return f"`{param.opts[0] if default else param.secondary_opts[0]}`"
        return "on" if default else ""
    if getattr(param, "count", False) or default is None or callable(default):
        return ""
    if isinstance(default, (list, tuple)):
        if not default:
            return ""
        default = ",".join(str(v) for v in default)
    if default == "":
        return ""
    return f"`{default}`"


# Click and Typer versions name the same types differently (TEXT/str, INTEGER/int).
TYPE_NAMES = {
    "text": "TEXT",
    "str": "TEXT",
    "string": "TEXT",
    "integer": "INTEGER",
    "int": "INTEGER",
    "float": "FLOAT",
    "boolean": "BOOLEAN",
    "bool": "BOOLEAN",
    "path": "PATH",
    "filename": "FILE",
}


def _type_name(param: Any) -> str:
    choices = getattr(param.type, "choices", None)
    if choices:
        return "[" + "|".join(str(c) for c in choices) + "]"
    name = (param.type.name or "").lower()
    return TYPE_NAMES.get(name, name.upper())


def _argument_name(param: Any) -> str:
    name = param.name.upper()
    if param.nargs == -1:
        name += "..."
    return name if param.required else f"[{name}]"


def command_block(command: Any, path: str, ctx: Any, heading: str) -> str:
    """Render the reference for one command."""
    lines = []
    if heading:
        lines += [f"{heading} `undatum {path}`", ""]
    capability = CAPABILITIES.get(path)
    if capability is not None:
        has_engine = any("--engine" in getattr(p, "opts", ()) for p in command.params)
        engines = ENGINES if has_engine else "python"
        lines += [
            f"**Reads:** {capability.reads} · **Writes:** {capability.writes} · "
            f"**Memory:** {capability.memory} · **Engines:** {engines}",
            "",
        ]
    arguments = [p for p in command.params if p.param_type_name == "argument"]
    usage = " ".join(["[OPTIONS]", *(_argument_name(arg) for arg in arguments)])
    lines += ["```text", f"undatum {path} {usage}", "```", ""]

    if arguments:
        lines += ["| Argument | Description |", "|----------|-------------|"]
        for arg in arguments:
            required = " (required)" if arg.required else ""
            name = arg.name.upper() + ("..." if arg.nargs == -1 else "")
            lines.append(f"| `{name}` | {_help(arg)}{required} |")
        lines.append("")

    options = [
        p
        for p in command.params
        if p.param_type_name == "option" and not p.hidden and "--help" not in p.opts
    ]
    if options:
        lines += ["| Option | Description | Default |", "|--------|-------------|---------|"]
        for opt in options:
            names = ", ".join(f"`{o}`" for o in sorted(opt.opts, key=len))
            if opt.secondary_opts:
                names += " / " + ", ".join(f"`{o}`" for o in opt.secondary_opts)
            if not opt.is_flag and not opt.count:
                names += f" {_escape(_type_name(opt))}"
            required = " (required)" if opt.required else ""
            lines.append(f"| {names} | {_help(opt)}{required} | {_default(opt)} |")
        lines.append("")

    aliases = getattr(command, "_undatum_aliases", {})
    if aliases:
        spelled = ", ".join(f"`{old}` → `{new}`" for old, new in sorted(aliases.items()))
        lines += [f"Deprecated spellings (removed in 2.0): {spelled}.", ""]
    return "\n".join(lines)


def _walk(command: Any, path: str, ctx: Any) -> Iterator[tuple[str, Any, Any]]:
    """Yield ``(path, command, ctx)`` for every visible leaf command."""
    if hasattr(command, "list_commands"):
        for name in command.list_commands(ctx):
            sub = command.get_command(ctx, name)
            if sub is None or sub.hidden:
                continue
            sub_path = f"{path} {name}".strip()
            sub_ctx = sub.context_class(sub, info_name=name, parent=ctx)
            yield from _walk(sub, sub_path, sub_ctx)
    else:
        yield path, command, ctx


def render_pages() -> dict[pathlib.Path, str]:
    """Return the generated block for each command page."""
    root = typer.main.get_command(app)
    root_ctx = root.context_class(root, info_name="undatum")
    blocks: dict[str, list[str]] = {}
    for path, command, ctx in _walk(root, "", root_ctx):
        page = path.split()[0]
        nested = " " in path
        blocks.setdefault(page, []).append(
            command_block(command, path, ctx, "###" if nested else "")
        )
    return {
        PAGES / f"{page}.md": "\n".join(
            [
                BEGIN,
                NOTE,
                "",
                "## Reference",
                "",
                *parts,
                "See also [shared options](/commands/shared-options).",
                END,
            ]
        )
        for page, parts in blocks.items()
    }


def apply_block(text: str, block: str) -> str:
    """Replace (or append) the generated block in a page."""
    if BEGIN in text and END in text:
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
        return text[:start] + block + text[end:]
    return text.rstrip("\n") + "\n\n" + block + "\n"


def new_page(path: pathlib.Path) -> str:
    name = path.stem
    return (
        f'---\ntitle: "{name}"\ndescription: "undatum {name} command reference"\n---\n'
        f"# `{name}`\n\n"
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when a page is stale")
    args = parser.parse_args(argv)

    stale = []
    for path, block in sorted(render_pages().items()):
        current = path.read_text(encoding="utf8") if path.exists() else new_page(path)
        updated = apply_block(current, block)
        if not updated.endswith("\n"):
            updated += "\n"
        if updated != (path.read_text(encoding="utf8") if path.exists() else ""):
            stale.append(path)
            if not args.check:
                path.write_text(updated, encoding="utf8")
    if args.check and stale:
        print("Stale command reference; run `python scripts/generate_cli_reference.py`:")
        for path in stale:
            print(f"  {path.relative_to(ROOT)}")
        return 1
    if not args.check:
        print(f"Updated {len(stale)} command pages")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
